# save as .github/workflows/runner.yml
name: runner

on:
  workflow_call:
    inputs:
      os:
        description: Operating System to run on
        required: false
        default: ubuntu
        type: string
      os_version:
        description: OS version
        required: false
        default: latest
        type: string
      raku_version:
        description: Raku version latest or 2023.10, etc.
        required: false
        default: latest
        type: string

env:
  zef_fetch_degree: 4
  zef_test_degree: 2
  # saving a few characters on the default C:\Users\RUNNER~1\AppData\Local\Temp trying to avoid the 260 chars
  # max path length limit of Windows
  # https://learn.microsoft.com/en-us/windows/win32/fileio/naming-a-file#maximum-path-length-limitation
  TMP: ${{ inputs.os == 'windows' && 'D:\T' || '/tmp' }}
  ZEF_CONFIG_TEMPDIR: ${{ inputs.os == 'windows' && 'D:\T' || '/tmp' }}
  TEMP: ${{ inputs.os == 'windows' && 'D:\T' || '/tmp' }}

jobs:
  runner:
    runs-on: ${{ inputs.os }}-${{ inputs.os_version }}
    steps:

    - name: Windows LongPathsEnabled
      if: ${{ inputs.os == 'windows' }}
      run: |
        New-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem" -Name "LongPathsEnabled" -Value 1 -PropertyType DWORD -Force
        mkdir -Force "${{ env.ZEF_CONFIG_TEMPDIR }}"

    - uses: Raku/setup-raku@v1
      with:
        raku-version: ${{ inputs.raku_version }}

    - uses: actions/checkout@v4

    - name: Install required modules
      run: zef --/test install JSON::Fast

    - name: Test Install Modules
      run: raku --optimize=3 -- bin/raku-module-health-check.raku resources results.json

    - name: Archive report
      uses: actions/upload-artifact@main
      with:
        name: stats-report
        path: results.json
